const androidStyles = {
  sidebarIcon: {
    marginLeft: 8,
    marginRight: 7,
    marginTop: 4,
  },
  header: {
    fontSize: 24,
    paddingBottom: 12,
    fontFamily: 'Arial',
  },
  header2: {
    fontSize: 16,
    paddingBottom: 12,
    fontFamily: 'Arial',
  },
  header3: {
    fontSize: 14,
    paddingBottom: 8,
    fontFamily: 'Arial',
  },
  headerIcon: {
    marginLeft: 8,
    marginRight: 8,
    marginTop: 2,
  },
  modal: {
    marginTop: 64,
    padding: 8,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  transaction_check: {
    display: 'flex',
    flexDirection: 'column',
    margin: 0,
    paddingTop: 2,
    paddingLeft: 0,
    paddingBottom: 0,
    paddingRight: 2,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#eeeeee',
    minHeight: 26,
    minWidth: 30,
    maxWidth: 30,
    fontFamily: 'Arial',
  },
  transaction_cell: {
    display: 'flex',
    flexDirection: 'column',
    margin: 0,
    paddingTop: 3,
    paddingLeft: 4,
    paddingBottom: 2,
    paddingRight: 4,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#eeeeee',
    textAlign: 'left',
    fontSize: 12,
    fontFamily: 'Arial',
  },
  transaction_cell_right: {
    display: 'flex',
    flexDirection: 'column',
    margin: 0,
    paddingTop: 3,
    paddingLeft: 4,
    paddingBottom: 2,
    paddingRight: 4,
    borderStyle: 'solid',
    borderColor: '#eeeeee',
    textAlign: 'right',
    fontSize: 12,
    fontFamily: 'Arial',
  },
  row_1: {
    minHeight: 26,
    fontFamily: 'Arial',
  },
  row_2: {
    color: '#white',
    backgroundColor: '#4c3f53',
    minHeight: 25,
  },
  checkboxView: {
    display: 'flex',
    flexDirection: 'row',
    marginBottom: 6,
    fontFamily: 'Arial',
  },
  txOneLineCategoryWidth: {
    minWidth: 150,
    maxWidth: 150,
    fontFamily: 'Arial',
  },
  txCategoryWidth: {
    minWidth: 150,
    maxWidth: 150,
    fontFamily: 'Arial',
  },
  checkboxText: {
    fontSize: 16,
    minWidth: 140,
    fontFamily: 'Arial',
  }
};

export default androidStyles;
