import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  sidebarIcon: {
    marginLeft: 8,
    marginRight: 8,
    marginTop: 4,
  },
  header: {
    fontSize: 32,
    paddingBottom: 40,
    fontFamily: 'Arial',
  },
  header2: {
    fontSize: 20,
    paddingBottom: 32,
    fontFamily: 'Arial',
  },
  header3: {
    fontSize: 18,
    paddingBottom: 16,
    fontFamily: 'Arial',
  },
  header4: {
    fontSize: 16,
    paddingBottom: 16,
    fontFamily: 'Arial',
  },
  headerIcon: {
    marginLeft: 8,
    marginRight: 8,
    marginTop: 3,
  },
  modal: {
    marginTop: 64,
    padding: 8,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  transaction_check: {
    display: 'flex',
    flexDirection: 'column',
    margin: 0,
    paddingLeft: 4,
    paddingRight: 4,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#eeeeee',
    minHeight: 26,
    fontFamily: 'Arial',
    alignContent: 'center',
    justifyContent: 'center',
  },
  transaction_cell: {
    display: 'flex',
    flexDirection: 'column',
    margin: 0,
    paddingTop: 3,
    paddingLeft: 4,
    paddingBottom: 2,
    paddingRight: 4,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#eeeeee',
    textAlign: 'left',
    fontFamily: 'Arial',
    alignContent: 'center',
    justifyContent: 'center',
  },
  transaction_cell_right: {
    display: 'flex',
    flexDirection: 'column',
    margin: 0,
    paddingTop: 3,
    paddingLeft: 4,
    paddingBottom: 2,
    paddingRight: 4,
    borderStyle: 'solid',
    borderColor: '#eeeeee',
    textAlign: 'right',
    fontFamily: 'Arial',
  },
  row_1: {
    minHeight: 26,
    fontFamily: 'Arial',
  },
  row_2: {
    color: '#e8e8e8',
    fontSize: 8,
    backgroundColor: '#4c3f53',
    minHeight: 25,
    fontFamily: 'Arial',
  },
  checkboxView: {
    display: 'flex',
    flexDirection: 'row',
    marginBottom: 10,
    marginHorizontal: 8,
    fontFamily: 'Arial',
  },
  txOneLineCategoryWidth: {
    minWidth: 200,
    maxWidth: 200,
    fontSize: 14,
    fontFamily: 'Arial',
    alignContent: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  txCategoryWidth: {
    minWidth: 225,
    maxWidth: 225,
    fontSize: 14,
    fontFamily: 'Arial',
    alignContent: 'center',
    justifyContent: 'center',
  },
  checkboxText: {
    fontSize: 16,
    paddingBottom: 0,
    minWidth: 200,
    fontFamily: 'Arial',
  },
  containerPadding: {
    display: 'flex',
    padding: 48,
  },
  containerSmallPadding: {
    display: 'flex',
    paddingVertical: 16,
  },
  container: {
    display: 'flex',
    flex: 1,
    fontFamily: 'Arial',
  },
  containerMarginBottom: {
    flex: 1,
    paddingBottom: 48,
    fontFamily: 'Arial',
  },
  flexy: {
    display: 'flex',
    fontFamily: 'Arial',
  },
  flex1: {
    display: 'flex',
    flex: 1,
    fontFamily: 'Arial',
  },
  transparent: {
    backgroundColor: 'rgba(50,50,50,0.7)',
  },
  flex1Border: {
    display: 'flex',
    flex: 1,
    fontFamily: 'Arial',
    borderWidth: 2,
    borderStyle: 'solid',
    margin: 48,
    borderRadius: 8,
  },
  containerCenter: {
    display: 'flex',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    fontFamily: 'Arial',
  },
  hide: {
    display: 'none',
  },
  leftsidebar: {
    fontSize: 12,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    marginTop: 12,
    marginLeft: 12,
    marginBottom: 12,
    marginRight: 4,
    paddingVertical: 8,
    paddingHorizontal: 6,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#eeeeee',
    borderRadius: 15,
    minWidth: 408,
    maxWidth: 408,
    fontFamily: 'Arial',
  },
  headerButtonView: {
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    marginTop: 8,
    fontFamily: 'Arial',
  },
  headerButton: {
    marginLeft: 16,
    width: 128,
    fontFamily: 'Arial',
  },
  headerRow: {
    display: 'flex',
    flexDirection: 'row',
    height: 32,
    fontFamily: 'Arial',
  },
  headerText: {
    fontFamily: 'Arial',
  },
  headerContent: {
    width: 200,
    paddingTop: 4,
    paddingLeft: 8,
    fontFamily: 'Arial',
  },
  txHeader: {
    display: 'flex',
    paddingTop: 6,
    fontFamily: 'Arial',
  },
  account: {
    paddingBottom: 12,
    fontFamily: 'Arial',
  },
  jumbotron: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    marginRight: 12,
    marginLeft: 0,
  },
  oneLineTransactions: {
    fontSize: 8,
    fontFamily: 'Arial',
    paddingHorizontal: 8,
    paddingVertical: 0,
  },
  transactions: {
    fontSize: 8,
    fontFamily: 'Arial',
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  transaction: {
    display: 'flex',
    flexDirection: 'row',
    flexGrow: 1,
    borderWidth: 0,
    fontFamily: 'Arial',
  },
  transaction_row_2_cell_color: {
    color: 'white',
  },
  txsplit_blank: {
    minHeight: 33,
    maxHeight: 33,
    minWidth: 46,
    maxWidth: 46,
    fontFamily: 'Arial',
  },
  txsplits: {
    fontSize: 8,
    fontFamily: 'Arial',
  },
  txsplit: {
    display: 'flex',
    flexDirection: 'row',
    margin: 0,
    padding: 0,
    borderWidth: 0,
    fontFamily: 'Arial',
  },
  modify_split: {
    display: 'flex',
    flexDirection: 'row',
    margin: 0,
    padding: 0,
    borderWidth: 0,
    fontFamily: 'Arial',
  },
  txsplit_row_hover: {
    backgroundColor: 'gray',
    color: 'white',
    cursor: 'pointer',
    fontSize: 24,
    fontFamily: 'Arial',
  },
  txsplit_row: {
  },
  txsplit_cell: {
    display: 'flex',
    flexDirection: 'column',
    margin: 0,
    paddingTop: 3,
    paddingLeft: 4,
    paddingBottom: 2,
    paddingRight: 4,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#eeeeee',
    fontFamily: 'Arial',
  },
  txsplit_cell_left: {
    textAlign: 'left',
    fontFamily: 'Arial',
  },
  txsplit_cell_right: {
    textAlign: 'right',
    fontFamily: 'Arial',
  },
  txsplit_row_del_hover: {
    backgroundColor: '#5b4266',
    cursor: 'auto',
  },
  txsplit_del: {
    display: 'flex',
    flexDirection: 'column',
    margin: 0,
    paddingTop: 3,
    paddingLeft: 4,
    paddingBottom: 2,
    paddingRight: 4,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#eeeeee',
    minWidth: 46,
    maxWidth: 46,
    fontFamily: 'Arial',
    alignItems: 'center',
  },
  grow: {
    display: 'flex',
    flex: 1,
    fontSize: 14,
  },
  collapsibleContent: {
    borderRadius: 5,
    borderWidth: 1,
    position: 'absolute',
    top: 60,
    zIndex: 2,
    elevation: 2,
  },
  homePageText: {
    fontSize: 14,
    fontFamily: 'Arial',
  },
  buttonView: {
    paddingTop: 8,
    fontFamily: 'Arial',
  },
  buttonWidth: {
    width: 128,
    paddingBottom: 24,
    paddingRight: 8,
    fontFamily: 'Arial',
  },
  largeButtonWidth: {
    width: 150,
    paddingBottom: 16,
    fontFamily: 'Arial',
  },
  accountText: {
    fontFamily: 'Arial',
  },
  bodyText: {
    fontSize: 16,
    paddingBottom: 32,
    fontFamily: 'Arial',
  },
  bodyTextSmallPad: {
    fontSize: 16,
    paddingBottom: 16,
    fontFamily: 'Arial',
  },
  checkView: {
    display: 'flex',
    flexDirection: 'row',
    paddingBottom: 24,
    fontFamily: 'Arial',
  },
  checkText: {
    fontSize: 16,
    paddingBottom: 0,
    fontFamily: 'Arial',
  },
  inputView: {
    display: 'flex',
    flexDirection: 'row',
    marginBottom: 10,
    marginHorizontal: 8,
    fontFamily: 'Arial',
  },
  inputText: {
    fontSize: 16,
    paddingBottom: 0,
    minWidth: 200,
    paddingTop: 4,
    fontFamily: 'Arial',
  },
  checkbox: {
    marginTop: 4,
  },
  sel_buttons: {
    marginTop: 10,
  },
  currencyView: {
    display: 'flex',
    minWidth: 140,
    alignContent: 'center',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  currency: {
    display: 'flex',
    textAlign: 'right',
    fontFamily: 'monospace',
    fontSize: 16,
    marginRight: 2,
  },
  indent1: {
    marginLeft: 6,
  },
  indent2: {
    marginLeft: 12,
  },
  jrow: {
    display: 'flex',
    flexDirection: 'row',
  },
  jcolumn: {
    display: 'flex',
    flexDirection: 'column',
  },
  txDateWidth: {
    minWidth: 100,
    maxWidth: 100,
    fontSize: 14,
    fontFamily: 'Arial',
    alignContent: 'center',
    justifyContent: 'center',
  },
  txCheckNoWidth: {
    minWidth: 82,
    maxWidth: 82,
    fontSize: 14,
    fontFamily: 'Arial',
    alignContent: 'center',
    justifyContent: 'center',
  },
  txStatusWidth: {
    minWidth: 65,
    maxWidth: 65,
    fontSize: 14,
    fontFamily: 'Arial',
    alignContent: 'center',
    justifyContent: 'center',
  },
  txAmountWidth: {
    alignContent: 'center',
    justifyContent: 'center',
    minWidth: 120,
    maxWidth: 120,
    textAlign: 'right',
    fontFamily: 'monospace',
    fontSize: 12,
  },
  txBalanceWidth: {
    minWidth: 120,
    maxWidth: 120,
    alignContent: 'center',
    justifyContent: 'center',
    textAlign: 'right',
    fontFamily: 'monospace',
    fontSize: 12,
  },
  txCommissionWidth: {
    minWidth: 126,
    maxWidth: 126,
    textAlign: 'right',
    fontFamily: 'monospace',
    fontSize: 12,
  },
  txNumSharesWidth: {
    minWidth: 82,
    maxWidth: 82,
    textAlign: 'right',
    fontFamily: 'monospace',
    fontSize: 12,
  },
  txSplitDescWidth: {
    minWidth: 200,
    maxWidth: 200,
    fontSize: 14,
    fontFamily: 'Arial',
  },
  txSplitCatWidth: {
    minWidth: 200,
    maxWidth: 200,
    fontSize: 14,
    fontFamily: 'Arial',
  },
  txSplitCurrencyWidth: {
    minWidth: 120,
    maxWidth: 120,
    textAlign: 'right',
    fontFamily: 'monospace',
    fontSize: 12,
  },
  width17: {
    minWidth: 17,
    maxWidth: 17,
  },
  width24: {
    minWidth: 25,
    maxWidth: 25,
    alignContent: 'center',
    justifyContent: 'center',
  },
  width50: {
    minWidth: 50,
    maxWidth: 50,
  },
  width65: {
    minWidth: 65,
    maxWidth: 65,
  },
  width82: {
    minWidth: 82,
    maxWidth: 82,
  },
  width100: {
    minWidth: 100,
    maxWidth: 100,
  },
  width123: {
    minWidth: 123,
    maxWidth: 123,
  },
  width150: {
    minWidth: 150,
    maxWidth: 150,
  },
  width200: {
    minWidth: 200,
    maxWidth: 200,
  },
  width300: {
    minWidth: 300,
    maxWidth: 300,
  },
  width346: {
    minWidth: 346,
    maxWidth: 346,
  },
  width350: {
    minWidth: 350,
    maxWidth: 350,
  },
  button: {
    flex: 1,
    alignSelf: 'flex-end',
    alignItems: 'center',
  },
  flex1Center: {
    flex: 1,
    justifyContent: 'center',
  },
  cameraButtonContainer: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: 'transparent',
    margin: 64,
  },
  cameraButtonText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: 'white',
  },
});

export { styles };
